### ISSUE TITLE
-J option doesn't work

### ISSUE THREAD

**Issue by leo-o** [andreyvit/fsmonitor.js#9]
```
Monitoring:  compiled
    filter:  **/*.js/**
    action:  minify.cmd
     subst:  file

C:\Users\Leo\AppData\Roaming\npm\node_modules\fsmonitor\lib\cli.js:265
                files = change.addedFiles.concat(change.modifiedFiles);
                                         ^

TypeError: Cannot read property 'concat' of undefined
    at C:\Users\Leo\AppData\Roaming\npm\node_modules\fsmonitor\lib\cli.js:265:4

    at C:\Users\Leo\AppData\Roaming\npm\node_modules\fsmonitor\lib\cli.js:327:1

    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by leo-o** [comment]
BTW, this option is not documented in README.md
